[theme]
primaryColor = "#B4472D"
backgroundColor = "#F8F7F2"
secondaryBackgroundColor = "#EEF1EC"
textColor = "#18222D"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
