import type { DomainId, LocalizedText } from "@/lib/domain-guides";

export interface WorkbenchGuide {
  title: LocalizedText;
  calculation: LocalizedText;
  use: LocalizedText;
  scope: LocalizedText;
}

const text = (es: string, en: string): LocalizedText => ({ es, en });

export const WORKBENCH_GUIDES: Record<DomainId, Record<string, WorkbenchGuide>> = {
  vida: {
    temporal: { title: text("Seguro temporal", "Term life"), calculation: text("Valúa un beneficio por fallecimiento que sólo opera durante el plazo elegido, y calcula la prima neta y la total.", "Values a death benefit that operates only during the selected term and calculates net and total premiums."), use: text("Comparar el costo de protección por plazo, edad, suma asegurada y tasa técnica.", "Compare the cost of protection by term, age, sum assured, and technical rate."), scope: text("Usa mortalidad sintética y recargos ilustrativos; no es una cotización comercial.", "Uses synthetic mortality and illustrative loadings; it is not a commercial quote.") },
    ordinario: { title: text("Vida ordinaria", "Whole life"), calculation: text("Valúa un beneficio por fallecimiento vitalicio bajo la tabla y la tasa técnica seleccionadas.", "Values a lifetime death benefit under the selected mortality table and technical rate."), use: text("Examinar cómo una cobertura sin vencimiento cambia la prima y la acumulación de reserva.", "Examine how coverage without expiry changes premium and reserve accumulation."), scope: text("No modela rescates, dividendos, selección médica ni persistencia.", "Does not model surrender values, dividends, underwriting, or persistency.") },
    dotal: { title: text("Seguro dotal", "Endowment insurance"), calculation: text("Combina un beneficio por fallecimiento durante el plazo con un beneficio de supervivencia al vencimiento.", "Combines a death benefit during the term with a survival benefit at maturity."), use: text("Separar el costo biométrico de fallecimiento del compromiso de ahorro al vencimiento.", "Separate biometric death cost from the savings commitment at maturity."), scope: text("Es un caso educativo sin rescates, participación ni gastos observados.", "It is an educational case without surrenders, participation, or observed expenses.") },
    comparar: { title: text("Comparación de productos", "Product comparison"), calculation: text("Aplica los mismos supuestos a temporal, ordinario y dotal para contrastar primas.", "Applies the same assumptions to term, whole life, and endowment products to compare premiums."), use: text("Entender qué parte de la diferencia proviene de la promesa contractual.", "Understand which part of the difference comes from the contractual promise."), scope: text("No recomienda un producto ni evalúa necesidades, liquidez o idoneidad del asegurado.", "Does not recommend a product or assess the insured's needs, liquidity, or suitability.") },
  },
  danos: {
    auto: { title: text("Tarificación de automóvil", "Motor rating"), calculation: text("Aplica factores de vehículo, zona, conductor y deducible a una tarifa base ilustrativa.", "Applies vehicle, zone, driver, and deductible factors to an illustrative base tariff."), use: text("Revisar en qué dirección y con qué magnitud mueve la prima cada factor de la tarifa.", "Audit the direction and magnitude of each rating relativity."), scope: text("Las tablas no son una tarifa AMIS oficial ni experiencia vigente de mercado.", "The tables are neither an official AMIS tariff nor current market experience.") },
    incendio: { title: text("Tarificación de incendio", "Fire rating"), calculation: text("Estima una prima a partir del valor expuesto, construcción, zona y uso del inmueble.", "Estimates a premium from exposed value, construction, zone, and property use."), use: text("Explorar cómo las características físicas del inmueble cambian el costo técnico relativo.", "Explore how physical characteristics change relative technical cost."), scope: text("No incorpora inspección, acumulaciones, PML ni catástrofe.", "Does not include inspection, accumulations, PML, or catastrophe risk.") },
    rc: { title: text("Responsabilidad civil", "Liability"), calculation: text("Relaciona límite, deducible y clase de actividad con una prima pedagógica.", "Relates limit, deductible, and activity class to a pedagogical premium."), use: text("Examinar el efecto relativo de la severidad potencial y de la retención.", "Examine the relative effect of potential severity and retention."), scope: text("No sustituye curvas de límites, experiencia de litigio ni clausulado real.", "Does not replace limit curves, litigation experience, or actual wording.") },
    bonus_malus: { title: text("Bonus–malus: transición por experiencia", "Bonus–malus: experience transition"), calculation: text("Mueve el nivel del asegurado según sus siniestros: sin siniestros baja un nivel; uno sube dos; dos o más suben tres. El nuevo nivel determina un factor de prima.", "Moves the insured's level according to claims: no claims lowers one level; one claim raises two; two or more raise three. The new level determines a premium factor."), use: text("Revisar una regla de tarificación por experiencia y ver cómo la historia individual modifica la prima futura relativa.", "Review an experience-rating rule and see how individual history changes the relative future premium."), scope: text("La escala es una convención educativa implementada aquí; no representa una tarifa mexicana única, vigente u obligatoria.", "The scale is an educational convention implemented here; it is not a single current or mandatory Mexican tariff.") },
    freq_sev: { title: text("Frecuencia–severidad", "Frequency–severity"), calculation: text("Combina una distribución para el número de siniestros con otra para su costo y simula la pérdida agregada.", "Combines a claim-count distribution with a claim-cost distribution and simulates aggregate loss."), use: text("Estudiar la prima pura, la variabilidad y las medidas de cola bajo supuestos explícitos.", "Study pure premium, variability, and tail measures under explicit assumptions."), scope: text("Los parámetros que capturas no se estiman a partir de experiencia, y el modelo no añade incertidumbre de parámetros.", "Entered parameters are not estimated from experience and exclude parameter uncertainty.") },
  },
  salud: {
    gmm: { title: text("Gastos médicos mayores", "Major medical"), calculation: text("Calcula una tarifa ilustrativa y el reparto contractual mediante deducible, coaseguro, tope y suma asegurada.", "Calculates an illustrative tariff and contractual cost sharing through deductible, coinsurance, cap, and sum insured."), use: text("Separar el precio estimado de la mecánica de pago de un siniestro.", "Separate estimated price from claim-payment mechanics."), scope: text("No incorpora experiencia, inflación médica, red, selección ni renovación.", "Does not include experience, medical inflation, network, underwriting, or renewal." ) },
    accidentes: { title: text("Accidentes personales", "Personal accident"), calculation: text("Valúa coberturas indemnizatorias por muerte, invalidez y gastos médicos accidentales.", "Values indemnity benefits for accidental death, disability, and medical expenses."), use: text("Comparar cómo suma, ocupación y coberturas modifican la prima ilustrativa.", "Compare how amount, occupation, and benefits modify the illustrative premium."), scope: text("No modela definiciones contractuales, exclusiones ni experiencia de frecuencia.", "Does not model contractual definitions, exclusions, or frequency experience.") },
  },
  pensiones: {
    ley73: { title: text("Pensión IMSS Ley 73", "IMSS Ley 73 pension"), calculation: text("Aplica semanas, salario promedio y edad de retiro a la regla simplificada de beneficio definido.", "Applies weeks, average wage, and retirement age to the simplified defined-benefit rule."), use: text("Entender la sensibilidad y la elegibilidad dentro de la ruta implementada.", "Understand sensitivity and eligibility within the implemented path."), scope: text("Es una proyección educativa; no determina derechos ni sustituye una resolución del IMSS.", "It is an educational projection; it does not determine rights or replace an IMSS resolution.") },
    ley97: { title: text("Pensión IMSS Ley 97", "IMSS Ley 97 pension"), calculation: text("Convierte un saldo individual en estimaciones de renta vitalicia y retiro programado.", "Converts an individual balance into life-annuity and programmed-withdrawal estimates."), use: text("Relacionar saldo, longevidad y tasa con el ingreso mensual estimado.", "Relate balance, longevity, and rate to estimated monthly income."), scope: text("Omite seguro de sobrevivencia, comisiones, ofertas reales y reglas completas.", "Omits survivor insurance, fees, actual offers, and complete rules.") },
    renta_vitalicia: { title: text("Renta vitalicia", "Life annuity"), calculation: text("Calcula el factor actuarial y la prima única de una renta contingente a supervivencia.", "Calculates the actuarial factor and single premium for a survival-contingent annuity."), use: text("Medir el costo de transferir longevidad bajo mortalidad, tasa y frecuencia dadas.", "Measure the cost of transferring longevity under given mortality, rate, and frequency."), scope: text("La mortalidad es sintética y no incluye gastos, capital ni selección de rentistas.", "Mortality is synthetic and excludes expenses, capital, and annuitant selection.") },
    conmutacion: { title: text("Funciones de conmutación", "Commutation functions"), calculation: text("Construye Dₓ, Nₓ, Cₓ y Mₓ desde supervivencia y descuento.", "Builds Dₓ, Nₓ, Cₓ, and Mₓ from survival and discounting."), use: text("Reproducir factores de seguro y anualidad y verificar identidades actuariales.", "Reproduce insurance and annuity factors and verify actuarial identities."), scope: text("Es infraestructura matemática; por sí sola no define un producto ni una tarifa.", "It is mathematical infrastructure; by itself it defines neither a product nor a tariff.") },
  },
  reservas: {
    chainladder: { title: text("Chain Ladder", "Chain Ladder"), calculation: text("Proyecta el desarrollo faltante mediante factores age-to-age y obtiene ultimate y reserva.", "Projects missing development through age-to-age factors and obtains ultimate and reserve."), use: text("Construir un estimador central reproducible cuando el patrón histórico es defendible.", "Build a reproducible central estimate when the historical pattern is defensible."), scope: text("No cuantifica por sí solo riesgo de modelo, cambios de mezcla, inflación ni cola no observada.", "By itself it does not quantify model risk, mix changes, inflation, or unobserved tail.") },
    bornhuetter: { title: text("Bornhuetter–Ferguson", "Bornhuetter–Ferguson"), calculation: text("Combina siniestros emergidos con una pérdida esperada previa para estimar el ultimate.", "Combines emerged claims with a prior expected loss to estimate ultimate."), use: text("Estabilizar años inmaduros y hacer visible el peso del supuesto previo.", "Stabilize immature years and make the weight of the prior assumption visible."), scope: text("La calidad depende directamente de primas y loss ratios seleccionados externamente.", "Quality depends directly on externally selected premiums and loss ratios.") },
    bootstrap: { title: text("Bootstrap ODP", "ODP bootstrap"), calculation: text("Remuestrea residuales ajustados y añade variación de proceso para formar una distribución predictiva.", "Resamples adjusted residuals and adds process variation to form a predictive distribution."), use: text("Examinar percentiles, error de predicción y asimetría condicionados al modelo.", "Examine percentiles, prediction error, and skewness conditional on the model."), scope: text("No convierte incertidumbre condicionada en una garantía ni cubre riesgo de modelo.", "Does not turn conditional uncertainty into a guarantee or cover model risk.") },
  },
  reaseguro: {
    quotashare: { title: text("Cuota parte", "Quota share"), calculation: text("Divide primas y siniestros en una proporción fija entre cedente y reasegurador.", "Splits premiums and claims in a fixed proportion between cedent and reinsurer."), use: text("Examinar la transferencia proporcional, la comisión y el resultado neto.", "Examine proportional transfer, commission, and net result."), scope: text("No incluye cláusulas, límites, sliding scale ni experiencia contractual completa.", "Does not include wording, limits, sliding scale, or complete treaty experience.") },
    xl: { title: text("Exceso de pérdida", "Excess of loss"), calculation: text("Aplica prioridad, capacidad y agregado a cada siniestro para separar retención y recuperación.", "Applies attachment, capacity, and aggregate to each claim to split retention and recovery."), use: text("Diseñar la capa que responde al intervalo de severidad que se desea transferir.", "Design the layer that responds to the severity interval intended for transfer."), scope: text("La prima y las reinstalaciones usan convenciones simplificadas, no una cotización de mercado.", "Premium and reinstatements use simplified conventions, not a market quote.") },
    stoploss: { title: text("Stop loss", "Stop loss"), calculation: text("Cubre la pérdida agregada que excede un attachment anual hasta un límite.", "Covers aggregate loss above an annual attachment up to a limit."), use: text("Estudiar la protección sobre la siniestralidad anual y el agotamiento del contrato.", "Study annual loss-ratio protection and treaty exhaustion."), scope: text("No modela dependencia temporal, ajuste de prima ni términos contractuales completos.", "Does not model temporal dependence, premium adjustment, or complete treaty terms.") },
  },
  regulatorio: {
    rcs: { title: text("Escenario agregado de RCS", "Aggregate RCS scenario"), calculation: text("Agrega módulos simplificados de vida, daños e inversión y compara el resultado con capital disponible.", "Aggregates simplified life, P&C, and investment modules and compares the result with available capital."), use: text("Examinar la diversificación y hacia dónde se mueve el índice capital/RCS.", "Examine diversification and the direction of the capital/RCS ratio."), scope: text("No implementa el modelo estocástico completo ni certifica cumplimiento CNSF.", "Does not implement the complete stochastic model or certify CNSF compliance.") },
    deducibilidad: { title: text("Deducibilidad fiscal", "Tax deductibility"), calculation: text("Evalúa una operación contra reglas y límites fiscales codificados para el caso.", "Evaluates a transaction against coded tax rules and limits for the case."), use: text("Hacer explícita la ruta lógica y los datos que determinan el resultado.", "Make the logical path and data determining the result explicit."), scope: text("Las tasas y citas requieren verificación jurídica vigente antes de cualquier uso real.", "Rates and citations require current legal verification before any real use.") },
    retenciones: { title: text("Retenciones fiscales", "Tax withholding"), calculation: text("Calcula una retención ilustrativa según concepto, monto y tipo de contribuyente.", "Calculates an illustrative withholding by concept, amount, and taxpayer type."), use: text("Revisar base, tasa y resultado de la regla implementada.", "Review the base, rate, and result of the implemented rule."), scope: text("No constituye asesoría fiscal y debe contrastarse con legislación y criterios vigentes.", "Does not constitute tax advice and must be checked against current law and criteria.") },
  },
};
